#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Ошибка: запустите скрипт от root (sudo -i)"
  exit 1
fi

PANEL_DIR="/usr/local/share/vpn-panel"

source "$PANEL_DIR/core.sh"
source "$PANEL_DIR/modules/users.sh"
source "$PANEL_DIR/modules/masterdns.sh"
source "$PANEL_DIR/modules/udp.sh"
source "$PANEL_DIR/modules/ws.sh"
source "$PANEL_DIR/modules/security.sh"
source "$PANEL_DIR/modules/traffic.sh"
source "$PANEL_DIR/modules/devicelimit.sh"
source "$PANEL_DIR/modules/banner.sh"
source "$PANEL_DIR/modules/maintenance.sh"
source "$PANEL_DIR/modules/torrent_block.sh"

while true; do
    header
    echo -e " MasterDnsVPN : $(get_service_status masterdnsvpn)"
    echo -e " UDP-Custom   : $(get_service_status udp-custom)"
    echo -e " WS Proxy     : $(get_service_status ws-proxy)"
    echo -e "${CYAN}────────────────────────────────────────────${NC}"
    echo -e " 1) 👥 Управление пользователями"
    echo -e " 2) 🕸️  WebSocket Proxy (Кастомный)"
    echo -e " 3) ⚡ UDP Custom (Управление)"
    echo -e " 4) 🌐 MasterDnsVPN"
    echo -e " 5) 🛡️  Безопасность и Оптимизация"
    echo -e " 6) 🚫 Блокировка торрентов"
    echo -e " 7) 🎨 Баннер при подключении"
    echo -e " 8) 🔄 Обновить скрипт ВПН"
    echo -e " 0) 🚪 Выход"
    echo -e "${CYAN}────────────────────────────────────────────${NC}"
    read -p "Выберите раздел [0-8]: " main_choice

    case $main_choice in
        1) menu_users ;;
        2) menu_ws ;;
        3) menu_service ;;
        4) menu_masterdns ;;
        5) menu_sec ;;
        6) menu_torrent_block ;;
        7) menu_banner ;;
        8)
           echo -e "\n${YELLOW}🔄 Запуск обновления...${NC}"
           bash <(curl -Ls https://raw.githubusercontent.com/zotac85/vpn-panel/main/install.sh)
           read -p "Нажмите Enter для продолжения..."
           ;;
        0) clear; exit 0 ;;
        *) echo -e "${RED}Неверный выбор.${NC}"; sleep 1 ;;
    esac
done
